# Generated by Django 6.0.6 on 2026-09-11 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ButtonEmojiOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64, unique=True)),
                ('custom_emoji_id', models.CharField(max_length=64)),
                ('placeholder', models.CharField(max_length=16)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Button Emoji Override',
                'verbose_name_plural': 'Button Emoji Overrides',
                'db_table': 'button_emoji_overrides',
            },
        ),
        migrations.CreateModel(
            name='EmojiOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=32, unique=True)),
                ('custom_emoji_id', models.CharField(max_length=64)),
                ('placeholder', models.CharField(max_length=16)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Emoji Override',
                'verbose_name_plural': 'Emoji Overrides',
                'db_table': 'emoji_overrides',
            },
        ),
    ]
